---
  - name: task for php7
    yum:
      name:  '{{ item }}'
      state: present
    with_items:
      - php70
      - php70-gd
      - php70-imap
      - php70-mbstring
      - php70-opcache
      - php70-mysqlnd
      - php70-pdo
      - php70-pecl-apcu
    notify: Restart apache service
  - name: copy index file to remote
    copy:
      src: index.php
      dest: /var/www/html
      owner: ec2-user
      group: ec2-user
# tasks file for php
